openapi: 3.0.0
info:
  title: A7 Analytics Platform - Algo management Algo management API Option Prices and Greeks API
  description: 'A7 Analytics Platform for the main T7 trading venues of Deutsche Börse Group and for the MDP feed of CME Group. The platform enables clients to perform pre/at/post trade analysis and to interact with market data and analytics.It provides clients access to the most granular un-normalized/genuine historical order book data (EOBI, MDP) as well as constructed order books, off-the-shelf analytics and allows them to build their own custom analytics utilizing algo functionality, which is a flexible high-performance framework based on historical order book data.<br/><br/> The A7 data can be accessed either via the <a href="https://a7.deutsche-boerse.com/">user interface</a> or via RESTful API.</br></br>

    The algo management API provides access to the A7 algos and their results. With the API it is possible to create, update, delete and run algos and to access the results of the algo runs. All available endpoints are described in detail below.<br/><br/>

    <b>Security measures:</b></br> In order to prevent unauthorized access to the API an authentication token must be used. A7 utilises the bearer authentication scheme for this purpose. The authentication token must be added to the header of each request message. Depending on the implementation it might be necessary to add the keyword "Bearer" to the token string as a prefix followed by a space.</br></br> A token can be generated at the <a href="https://a7.deutsche-boerse.com/">A7 user interface</a>. After login the user has to click on the user icon in the upper right corner, click on <b>API token generation</b> and finally click on <b>Request API key</b>. The generated token will be displayed directly in the user interface.<br/><br/>

    '
  contact:
    name: Deutsche Börse Data & Analytics
    url: https://www.mds.deutsche-boerse.com
    email: analytics@deutsche-boerse.com
  version: 1.0.2
servers:
- url: /api/v1
  description: A7 production environment
security:
- bearerAuth: []
tags:
- name: Option Prices and Greeks
paths:
  /aidataset/OPT/{symbol}:
    get:
      tags:
      - Option Prices and Greeks
      summary: gets live options prices
      description: "live (delayed) prices for options on European stocks and indices including:<br/>\n  * reference spot price, bid/ask screen price, fair value price (based on surface calibration), implicit volatility, forward<br/>\n  * greeks : delta, vega<br/>\n\nCanari.dev computes AI-generated forecast signals indicating which option is over/underpriced, based on the holders strategy (buy and hold until maturity, 1 hour to 2 days holding horizon...). From these signals is derived a \"Canari price\" which is also available in this live tables.<br/> The delay ranges from 15 to 40 minutes depending on underlyings.\n"
      operationId: getOPT
      parameters:
      - $ref: '#/components/parameters/symbol'
      responses:
        200:
          description: successful operation
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/prices'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
  /aidataset/OPT/{symbol}/{maturity}:
    get:
      tags:
      - Option Prices and Greeks
      summary: gets live options prices for a given maturity
      description: "live (delayed) prices for options on European stocks and indices including:<br/>\n  * reference spot price, bid/ask screen price, fair value price (based on surface calibration), implicit volatility, forward<br/>\n  * greeks : delta, vega<br/>\n\nCanari.dev computes AI-generated forecast signals indicating which option is over/underpriced, based on the holders strategy (buy and hold until maturity, 1 hour to 2 days holding horizon...). From these signals is derived a \"Canari price\" which is also available in this live tables.<br/> The delay ranges from 15 to 40 minutes depending on underlyings.\n"
      operationId: getOPTmat
      parameters:
      - $ref: '#/components/parameters/symbol'
      - $ref: '#/components/parameters/maturity'
      responses:
        200:
          description: successful operation
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/prices'
            application/gzip:
              schema:
                $ref: '#/components/schemas/prices'
                format: binary
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
components:
  parameters:
    symbol:
      name: symbol
      in: path
      description: unique trading symbol identifier
      required: true
      schema:
        $ref: '#/components/schemas/symbol'
    maturity:
      name: maturity
      in: path
      description: option maturity
      required: true
      schema:
        $ref: '#/components/schemas/maturity'
  schemas:
    maturity:
      description: option maturity
      type: string
      pattern: ^[01][0-9]{3}$
      example: '0625'
    symbol:
      description: trading symbol
      type: string
      enum:
      - OESX
      - ODAX
      - OSMI
      - OESB
      - OVS2
      - ITK
      - ABBN
      - ASM
      - ADS
      - AIR
      - EAD
      - ALV
      - AXA
      - BAS
      - BBVD
      - BMW
      - BNP
      - BAY
      - DBK
      - DB1
      - DPW
      - DTE
      - EOA
      - ENL5
      - INN
      - IBE
      - IFX
      - IES5
      - PPX
      - LOR
      - MOH
      - LIN
      - DAI
      - MUV2
      - NESN
      - NOVN
      - PHI1
      - REP
      - ROG
      - SAP
      - SNW
      - BSD2
      - SND
      - SIE
      - SGE
      - SREN
      - TNE5
      - TOTB
      - UBSN
      - CRI5
      - SQU
      - VO3
      - ANN
      - ZURN
      example: DB1
    prices:
      description: array of prices for options and greeks
      type: array
      items:
        type: object
        properties:
          Snapshot_time_(GMT):
            type: string
            format: date-time
          Eurex_code:
            type: string
          Maturity:
            type: string
          Option type:
            type: string
          Exercise:
            type: string
          StrikePrice:
            type: number
          Calibrated price:
            type: number
          Canari Price:
            type: number
          Calibrated Implied Vol:
            type: number
          Delta:
            type: number
          Vega:
            type: number
          Forward:
            type: number
          MDE:
            type: number
          DIV:
            type: number
          CSA:
            type: number
          SMI:
            type: number
          Underlying_full_name:
            type: string
      example: 'Snapshot_time_(GMT),Eurex code,Maturity,Option type,Exercise,StrikePrice,Calibrated price,Canari Price,Calibrated Implied Vol,Delta,Vega,Forward,MDE,DIV,CSA,SMI,Underlying_full_name

        2024-06-21 12:50:00,DB1,20240719,Call,American,178.0,14.6155,14.6411,22.4972,0.8894,0.1015,192.011,0.0,0.0,2.578,-0.0218,Deutsche Boerse

        2024-06-21 12:50:00,DB1,20240719,Call,American,180.0,12.7722,12.8019,21.4055,0.8639,0.1175,192.011,0.0,0.0,2.578,-0.0218,Deutsche Boerse

        2024-06-21 12:50:00,DB1,20240719,Call,American,182.0,10.9807,11.0151,20.392,0.8309,0.1358,192.011,0.0,0.0,2.578,-0.0218,Deutsche Boerse

        2024-06-21 12:50:00,DB1,20240719,Call,American,184.0,9.259,9.2987,19.4604,0.7887,0.1558,192.011,0.0,0.0,2.578,-0.0218,Deutsche Boerse

        2024-06-21 12:50:00,DB1,20240719,Call,American,186.0,7.6288,7.6738,18.6084,0.7357,0.1762,192.011,0.0,0.0,2.578,-0.0218,Deutsche Boerse

        '
  responses:
    '404':
      description: not found
    '400':
      description: bad request
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
    '401':
      description: authorization failed
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
    '403':
      description: access denied
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
