openapi: 3.2.0
info:
  title: A7 Analytics Platform - Market data insights Latency…
  description: A7 Analytics Platform for the main T7 trading venues of Deutsche Börse Group.
  contact:
    name: Deutsche Börse Data & Analytics
    url: https://www.mds.deutsche-boerse.com
    email: analytics@deutsche-boerse.com
  version: 1.0.1
servers:
- url: /api/v1
  description: A7 production environment
security:
- bearerAuth: []
tags:
- name: Latency Historgram
paths:
  /insights/latencies/{date}/{trigger}/{target}/{regime}/{target_action}:
    get:
      tags:
      - Latency Historgram
      summary: Retrieve result of given latencies query
      description: The request queries the latencies and returns the matching results.
      operationId: queryInsights
      parameters:
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/trigger'
      - $ref: '#/components/parameters/target'
      - $ref: '#/components/parameters/regime'
      - $ref: '#/components/parameters/target_action'
      - $ref: '#/components/parameters/format'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatenciesInsightsResultsJson'
            text/csv:
              schema:
                $ref: '#/components/schemas/LatenciesInsightsResultsCsv'
            application/gzip:
              schema:
                $ref: '#/components/schemas/LatenciesInsightsResultsJson'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
components:
  parameters:
    date:
      name: date
      in: path
      description: Date (fact date) of the data to be retrieved (as YYYYMMDD)
      example: 20220121
      required: true
      schema:
        type: string
        pattern: ^20\d{2}[01]\d[0-3]\d$
    trigger:
      name: trigger
      in: path
      description: Trigger product
      example: FDAX
      required: true
      schema:
        type: string
    format:
      name: format
      in: query
      description: Defines the format of the response.
      schema:
        type: string
        enum:
        - csv
        - json
        default: json
    regime:
      name: regime
      in: path
      description: Latency regime
      required: true
      schema:
        type: string
        enum:
        - FPGA
        - SOFTWARE
        default: FPGA
    target:
      name: target
      in: path
      description: Target product
      example: FDAX
      required: true
      schema:
        type: string
    target_action:
      name: target_action
      in: path
      description: Target action
      required: true
      schema:
        type: string
        enum:
        - TRADE
        - BOOK
        - ALL
        default: ALL
  schemas:
    LatenciesInsightsResultsJson:
      properties:
        data:
          type: array
          items:
            type: object
      example:
      - Date: '20220201'
        TriggerProduct: FDAX
        TargetProduct: FDAX
        LatencyRegime: FPGA
        TargetAction: TRADE
        Latency: '2712.0'
        Count: '0'
      - Date: '20220201'
        TriggerProduct: FDAX
        TargetProduct: FDAX
        LatencyRegime: FPGA
        TargetAction: TRADE
        Latency: '2713.0'
        Count: '2'
      - Date: '20220201'
        TriggerProduct: FDAX
        TargetProduct: FDAX
        LatencyRegime: FPGA
        TargetAction: TRADE
        Latency: '2714.0'
        Count: '1'
      - Date: '20220201'
        TriggerProduct: FDAX
        TargetProduct: FDAX
        LatencyRegime: FPGA
        TargetAction: TRADE
        Latency: '2715.0'
        Count: '6'
    LatenciesInsightsResultsCsv:
      type: string
      example: 'Date,TriggerProduct,TargetProduct,LatencyRegime,TargetAction,Latency,Count

        20220201,FDAX,FDAX,FPGA,TRADE,2712.0,0

        20220201,FDAX,FDAX,FPGA,TRADE,2713.0,2

        20220201,FDAX,FDAX,FPGA,TRADE,2714.0,1

        20220201,FDAX,FDAX,FPGA,TRADE,2715.0,6

        '
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
