openapi: 3.2.0
info:
  title: A7 Analytics Platform - CME Market data API (MDP) Sending…
  description: A7 Analytics Platform for the CME Group.
  contact:
    name: Deutsche Börse Data & Analytics
    url: https://www.mds.deutsche-boerse.com
    email: analytics@deutsche-boerse.com
  version: 1.1.0
servers:
- url: /api/v1
  description: A7 production environment
security:
- bearerAuth: []
tags:
- name: Sending times, packets, messages
paths:
  /mdp/{exchange}/{date}/{asset}/{securityId}:
    get:
      tags:
      - Sending times, packets, messages
      summary: retrieves list of packets' sending times, or complete packets
      description: The request delivers a list of the available sending times, or alternatively complete packets for the selected exchange, trading day, asses and security.
      operationId: getTransactTimes
      parameters:
      - $ref: '#/components/parameters/exchange'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/asset'
      - $ref: '#/components/parameters/securityID'
      - $ref: '#/components/parameters/mode'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/from'
      - $ref: '#/components/parameters/to'
      - $ref: '#/components/parameters/msgSeqNum'
      - $ref: '#/components/parameters/templateID'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/sendingTimes'
                - $ref: '#/components/schemas/packetDetails'
                - $ref: '#/components/schemas/InternalError'
            application/gzip:
              schema:
                oneOf:
                - $ref: '#/components/schemas/sendingTimes'
                - $ref: '#/components/schemas/packetDetails'
                - $ref: '#/components/schemas/InternalError'
                format: binary
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
  /mdp/{exchange}/{date}/{asset}/{securityId}/{sendingTime}:
    get:
      tags:
      - Sending times, packets, messages
      summary: retrieves packet details
      description: 'The request delivers the details of the packet identified by the selected exchange, trading day, asset, security and packet''s sending time.

        For a detailed description of the different message types please refer to the CME MDP documentation.'
      operationId: getPacketDetails
      parameters:
      - $ref: '#/components/parameters/exchange'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/asset'
      - $ref: '#/components/parameters/securityID'
      - $ref: '#/components/parameters/sendingTime'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/packetDetail'
                - $ref: '#/components/schemas/InternalError'
            application/gzip:
              schema:
                oneOf:
                - $ref: '#/components/schemas/packetDetail'
                - $ref: '#/components/schemas/InternalError'
                format: binary
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
components:
  parameters:
    templateID:
      name: templateId
      in: query
      description: array of templateIDs used as a filter to select packets (multiple values are separated by comma)
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
          minimum: 0
          example: 46
      style: form
      explode: false
    msgSeqNum:
      name: msgSeqNum
      in: query
      description: array of packet's sequence numbers used as a filter to select packets (multiple values are separated by comma)
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int64
          minimum: 1
          example: 22902064
      style: form
      explode: false
    exchange:
      name: exchange
      in: path
      description: exhange identifier code
      required: true
      schema:
        $ref: '#/components/schemas/exchange'
    securityID:
      name: securityId
      in: path
      description: unique security identifier
      required: true
      schema:
        $ref: '#/components/schemas/securityID'
    sendingTime:
      name: sendingTime
      in: path
      description: packet's sending time
      required: true
      schema:
        $ref: '#/components/schemas/timestamp'
    from:
      name: from
      in: query
      description: array of packet's sending times as start times for (multiple) time interval selection (multiple values are separated by comma)
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/timestamp'
      style: form
      explode: false
    date:
      name: date
      in: path
      required: true
      description: trading day in the format YYYYMMDD
      schema:
        $ref: '#/components/schemas/date'
    mode:
      name: mode
      in: query
      description: "Define the output format for the response.<br/> Mode options:\n  * `reference` (default) - Shows a list of the referencing IDs\n  * `detailed` - Shows a list of packets with messages including their details\n"
      required: false
      schema:
        type: string
        enum:
        - reference
        - detailed
        default: reference
    asset:
      name: asset
      in: path
      description: unique asset identifier
      required: true
      schema:
        $ref: '#/components/schemas/asset'
    limit:
      name: limit
      in: query
      description: max number of elements in the response
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 10000
        default: 1000
        example: 10
    to:
      name: to
      in: query
      description: packet's sending time as a global end time for (multiple) time interval selection
      required: false
      schema:
        $ref: '#/components/schemas/timestamp'
      example: null
  schemas:
    exchange:
      description: exchange mic
      type: string
      minLength: 4
      maxLength: 4
      example: XCME
    packetDetail:
      description: packet's details
      type: object
      properties:
        Messages:
          description: packet header, size header, messages
          type: object
    securityID:
      description: Security ID
      type: integer
      format: int32
      example: 206299
    timestamp:
      description: timestamp as number of nanoseconds since Unix epoch
      type: string
      example: '1673390700086106154'
    sendingTimes:
      type: object
      properties:
        SendingTimes:
          description: array of packets' sending times
          type: array
          items:
            $ref: '#/components/schemas/timestamp'
          example:
          - '1673390700086106154'
          - '1673390700088531122'
          - '1673390700088549040'
    date:
      description: date representation
      type: integer
      format: int32
      minLength: 8
      maxLength: 8
      example: 20230111
    asset:
      description: asset code also known as product code
      type: string
      maxLength: 6
      example: ES
    InternalError:
      properties:
        success:
          type: string
          example: false
        message:
          type: string
          example: Error message
      required:
      - success
      - message
    packetDetails:
      type: object
      properties:
        Packets:
          description: array of packets' details
          type: array
          items:
            description: array of packet's details
            type: array
            items:
              description: packet header, size header, messages
              type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
