openapi: 3.2.0
info:
  title: A7 Analytics Platform - Option Analytics Datasets API
  description: A7 Analytics Platform for the main T7 trading venues of Deutsche Börse Group.
  contact:
    name: Deutsche Börse Data & Analytics
    url: https://www.mds.deutsche-boerse.com
    email: analytics@deutsche-boerse.com
  version: 1.0.1
servers:
- url: /api/v1
  description: A7 production environment
security:
- bearerAuth: []
tags:
- name: Datasets
paths:
  /aidataset:
    get:
      tags:
      - Datasets
      summary: gets available datasets with description
      description: datasets with description
      operationId: getDatasetDescs
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datasetdescs'
            application/gzip:
              schema:
                $ref: '#/components/schemas/datasetdescs'
                format: binary
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
  /aidataset/:
    get:
      tags:
      - Datasets
      summary: gets available datasets
      description: datasets
      operationId: getDatasets
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datasets'
            application/gzip:
              schema:
                $ref: '#/components/schemas/datasets'
                format: binary
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
components:
  schemas:
    datasetdescs:
      description: dictionary of datasets
      type: object
      additionalProperties:
        description: dataset description
        type: string
      example:
        OPT: Live options prices,
        IV: Implied volatility,
        RV: Realized volatility (intraday, maturity expressed as EWM, span in business days)
    dataset:
      description: dataset name
      type: string
      enum:
      - OPT
      - IV
      - RV
      - DIV
      - SMI
      - FWD
      example: OPT
    datasets:
      description: array of dataset names
      type: array
      items:
        $ref: '#/components/schemas/dataset'
      example:
      - OPT
      - IV
      - RV
  responses:
    '404':
      description: not found
    '403':
      description: access denied
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
    '400':
      description: bad request
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
    '401':
      description: authorization failed
      content:
        text/plain:
          schema:
            type: string
          example: specific error message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
